//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using Microsoft.EntityFrameworkCore;

    public class WebAppContext : DbContext
    {

        public WebAppContext(DbContextOptions<WebAppContext> options) : base(options)
        {
        }
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<File_Resource> File_Resource { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Group_Joining_Request> Group_Joining_Request { get; set; }
        public DbSet<Industry_Lecturer_Project> Industry_Lecturer_Project { get; set; }
        public DbSet<Lecturer> Lecturers { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Project_Choice> Project_Choice { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Student_Project> Student_Project { get; set; }
        public DbSet<Student_Project_Extra> Student_Project_Extra { get; set; }
		protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }

}
