//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class File_Resource
    {
        [Key]
        public int file_resource_id { get; set; }
        public string name { get; set; }
        public string extension { get; set; }
        public byte[] data { get; set; }
        public int announcement_id { get; set; }
    
        public virtual Announcement Announcement { get; set; }
    }
}
