//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Industry_Lecturer_Project
    {
        [Key]
        public int project_id { get; set; }
        public string project_milestones { get; set; }
        public string company_name { get; set; }
        public string company_postal_address { get; set; }
        public string company_telephone_number { get; set; }
        public string company_fax_number { get; set; }
        public string company_email_address { get; set; }
        public Nullable<bool> company_sponsorship_willingness { get; set; }
        public string company_liaison_officer_name { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
