//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    
	public partial class Project_Choice
    {
		[Key]
		public int project_choice_id { get; set; }
		[ForeignKey("Student")]
        public int student_id { get; set; }
		[ForeignKey("Project")]
        public int project_id { get; set; }
        public int ranking_precedence { get; set; }
        public System.DateTime choice_date { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
    }
}
