//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Student_Project
    {
		[Key]
        public int project_id { get; set; }
        public string project_background { get; set; }
        public string strategy_and_approach { get; set; }
        public string merits_comparison { get; set; }
        public string commercialisation_strategy { get; set; }
        public string project_milestones_and_workload_allocation { get; set; }
        public string problems_and_countermeasures { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
