//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Student_Project_Extra
    {
        [Key]
		public int Id { get; set; }
        public string field_name { get; set; }
        public string description_text { get; set; }
        public string text_value { get; set; }
        public Nullable<int> project_id { get; set; }
    }
}
